spring:
  config:
    import:
      - classpath:config/common/jpa-detail-logging.yaml
  datasource:
    url: jdbc:mysql://${DATABASE_MYSQL_HOST}:${DATABASE_MYSQL_PORT:3306}/${DATABASE_MYSQL_SCHEMA:rms}?${DATABASE_MYSQL_OPTION:charset=utf8mb4,utf8&createDatabaseIfNotExist=true}
    username: ${DATABASE_MYSQL_USER:rms}
    password: ${DATABASE_MYSQL_PASSWORD:rms123}
  mail:
    properties:
      mail:
        debug: true
  session:
    redis:
      namespace: ${REDIS_NAMESPACE:local.v1}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}

security:
  jwt:
    secret: ${JWT_SECRET:local-development-secret}

---
application:
  deploy:
    environment: "local"
