environment: production

server:
  port: 8080

database:
  mysql:
    max_idle_conns: 50
    max_open_conns: 200
    conn_max_lifetime: 30m

logging:
  level: info
  format: json

cors:
  allowed_origins:
    - https://rms.bellsoft.net
